# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER ruoyi

# 挂载目录
VOLUME /home/ruoyi
# 创建目录
RUN mkdir -p /home/ruoyi
# 指定路径
WORKDIR /home/ruoyi
# 复制jar文件到路径
COPY ./jar/qa-hero-gateway.jar /home/ruoyi/qa-hero-gateway.jar
# 启动网关服务
ENTRYPOINT ["java","-jar","qa-hero-gateway.jar"]